[package]
name = "scpi_derive"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[lib]
name = "scpi_derive"
proc-macro = true

[dependencies]
pest = "1.0.0-beta"
pest_derive = "1.0.0-beta"
proc-macro2 = "0.2.1"
quote = "0.4"
syn = "0.12"
